rootProject.name=balance
profile=dev
version=2.0.40

# Build properties
node_version=12.13.0
npm_version=6.13.0
yarn_version=1.19.0

# Dependency versions
jhipsterFrameworkDependenciesVersion=9.0.0
springBootVersion=4.0.4
springCloudVersion=2025.1.0
hibernate_version=7.3.1.Final
mapstruct_version=1.6.3
archunit_junit5_version=0.12.0

#liquibase_hibernate5_version=3.6
liquibaseTaskPrefix=liquibase

jaxb_runtime_version=2.3.2
securityJwtVersion=1.1.1.RELEASE
springdocVersion=3.0.3

# gradle plugin version
grgit_plugin_version=4.1.1
jib_plugin_version=3.5.3
git_properties_plugin_version=2.5.4
apt_plugin_version=0.21
liquibase_plugin_version=2.0.1
checkstyle_version=13.4.0
spotbugs_version=6.4.8
sonarqube_plugin_version=7.3.0.8198
pmd_version=7.23.0
spring_dependency_management_version=1.1.7
#zalandoVersion=0.29.1

# Other dependency versions
lombok_version=1.18.42
jacocoVersion=0.8.14
equalsVerifierVersion=3.19.1
commonsCodecVersion=1.17.2
commonsIoVersion=2.21.0
commonsCollections4Version=4.5.0
commonsTextVersion=1.13.0
guavaVersion=33.4.0-jre
logstashLogbackEncoderVersion=8.0
caffeineVersion=3.2.0
swaggerCodegenVersion=3.0.68
hibernateValidationVersion=8.0.2.Final
jsonSchemaValidatorVersion=3.0.2
httpClient5Version=5.6.1
httpCore5Version=5.4.2

## XM custom properties
xm_commons_version=5.0.30
# jhipster-needle-gradle-property - JHipster will add additional properties here

## below are some of the gradle performance improvement settings that can be used as required, these are not enabled by default

## The Gradle daemon aims to improve the startup and execution time of Gradle.
## The daemon is enabled by default in Gradle 3+ setting this to false will disable this.
## TODO: disable daemon on CI, since builds should be clean and reliable on servers
## https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:ways_to_disable_gradle_daemon
## un comment the below line to disable the daemon

#org.gradle.daemon=false

## Specifies the JVM arguments used for the daemon process.
## The setting is particularly useful for tweaking memory settings.
## Default value: -Xmx1024m -XX:MaxPermSize=256m
## un comment the below line to override the daemon defaults

#org.gradle.jvmargs=-Xmx1024m -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

## When configured, Gradle will run in incubating parallel mode.
## This option should only be used with decoupled projects. More details, visit
## http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
## un comment the below line to enable parallel mode

#org.gradle.parallel=true

## Enables new incubating mode that makes Gradle selective when configuring projects.
## Only relevant projects are configured which results in faster builds for large multi-projects.
## http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:configuration_on_demand
## un comment the below line to enable the selective mode

#org.gradle.configureondemand=true
