# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
management:
    opentelemetry:
        tracing:
            export:
                otlp:
                    endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4317}
    tracing:
        export:
            enabled: ${MANAGEMENT_TRACING_EXPORT_ENABLED:false}
        propagation:
            type: w3c
        sampling:
            probability: 1.0
    otlp:
        metrics:
            export:
                enabled: ${MANAGEMENT_OTLP_METRICS_EXPORT_ENABLED:false}
                url: ${OTEL_EXPORTER_OTLP_HTTP_BASE_URL:http://localhost:4318}/v1/metrics
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile", "jhimetrics", "prometheus" ]
    endpoint:
        health:
            show-details: when-authorized
    info:
        git:
            mode: full
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
    metrics:
        enable:
            http: true
            jvm: true
            logback: true
            process: true
            system: true
        export:
            prometheus:
                enabled: true
                step: 60
spring:
    application:
        name: balance
    main:
        allow-bean-definition-overriding: true
    cloud:
        inetutils:
            preferredNetworks:
                - 192.168.
                - 10.
        consul:
            discovery:
                query-passing: true
                healthCheckPath: /management/health
                instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
            config:
                watch:
                    enabled: false
    jackson:
        default-property-inclusion: non_empty
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.springframework.boot.hibernate.SpringImplicitNamingStrategy
        properties:
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
    liquibase:
        default-schema: XM
        change-log: classpath:config/liquibase/master.xml
security:
    oauth2:
        resource:
            filter-order: 3

server:
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    security:
        content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:"
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: balance@localhost
    swagger:
        default-include-pattern: /api/.*
        title: balance API
        description: balance API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

xm-config:
    enabled: true
    xm-config-url: http://config
    kafka-config-topic: config_topic

application:
    tenant-ignored-path-list: /v2/api-docs, /api/profile-info, /swagger-resources/configuration/ui, /management/health
    timelines-enabled: true
    db-schema-suffix:
    kafka-enabled: true
    kafka-system-queue: system_queue
    retry:
        max-attempts: 3
        delay: 1000 #in milliseconds
        multiplier: 2
    pocket-charging-batch-size: 100
    lep:
        tenant-script-storage: XM_MS_CONFIG
        full-recompile-on-lep-update: false
    specification-name: balancespec.yml
    specification-path-pattern: /config/tenants/{tenantName}/balance/${application.specification-name}

gracefulShutdown:
    enabled: false
    shutdownDelay:
